#ifndef DUNE_ALUGRID_CHECKPARALLEL_HH
#define DUNE_ALUGRID_CHECKPARALLEL_HH

#if HAVE_MPI
  #define ALU3DGRID_PARALLEL 1
#else 
  #define ALU3DGRID_PARALLEL 0
#endif

#endif // #ifndef DUNE_ALUGRID_CHECKPARALLEL_HH
